-- Living Survivor - Built-in translations
-- Loaded as shared Lua to be available from client code

LivingSurvivorLang = {}

LivingSurvivorLang["EN"] = {

    -- Moodle thoughts
    Endurance_1_1 = "Breathe...",
    Endurance_1_2 = "I can hold on a bit more",
    Endurance_1_3 = "Focus on surviving",
    Endurance_2_1 = "I'm out of breath",
    Endurance_2_2 = "I'm pushing too hard",
    Endurance_2_3 = "My lungs are burning",
    Endurance_3_1 = "I'm exhausted",
    Endurance_3_2 = "I'm at my limit",
    Endurance_3_3 = "Fatigue is destroying me",
    Endurance_4_1 = "I... can't... even move",
    Endurance_4_2 = "I have no strength left",
    Endurance_4_3 = "I can barely breathe",

    HeavyLoad_1_1 = "This is heavy",
    HeavyLoad_1_2 = "I'm carrying too much",
    HeavyLoad_1_3 = "This is weighing me down",
    HeavyLoad_2_1 = "I should drop something",
    HeavyLoad_2_2 = "This is slowing me down",
    HeavyLoad_2_3 = "I can't run with this",
    HeavyLoad_3_1 = "The weight is destroying me",
    HeavyLoad_3_2 = "I can't even walk with this",
    HeavyLoad_3_3 = "My back hurts too much",
    HeavyLoad_4_1 = "I... can't... take it anymore...",
    HeavyLoad_4_2 = "If I don't drop something I'll have an accident",
    HeavyLoad_4_3 = "The weight is slowly killing me",

    Angry_1_1 = "How annoying",
    Angry_1_2 = "I'm pissed off",
    Angry_1_3 = "I'm not in the mood",
    Angry_2_1 = "Everything's going wrong",
    Angry_2_2 = "I'm losing my patience",
    Angry_2_3 = "This is getting on my nerves",
    Angry_3_1 = "Fuck this shit, I'm fed up",
    Angry_3_2 = "I'd love to break something",
    Angry_3_3 = "I'm about to explode",
    Angry_4_1 = "I'm going to destroy everything",
    Angry_4_2 = "I'm so fucking done with this shit",
    Angry_4_3 = "I'm going to kill them all",

    Stress_1_1 = "So stressful",
    Stress_1_2 = "I'm tense",
    Stress_1_3 = "I'm on edge",
    Stress_2_1 = "Fuck, I can't take it anymore",
    Stress_2_2 = "Can't stop overthinking",
    Stress_2_3 = "My head is spinning",
    Stress_3_1 = "This is too much, I can't handle my life",
    Stress_3_2 = "The pressure is going to kill me",
    Stress_3_3 = "I'm about to break",
    Stress_4_1 = "I can't take one more second, God please make it stop",
    Stress_4_2 = "Please make it stop",
    Stress_4_3 = "For the love of God, end this now",

    Thirst_1_1 = "A drink would be nice",
    Thirst_1_2 = "I'm thirsty",
    Thirst_1_3 = "My mouth is dry",
    Thirst_2_1 = "I need to drink something",
    Thirst_2_2 = "My throat is burning",
    Thirst_2_3 = "I should drink or I'll get worse",
    Thirst_3_1 = "I'm getting dehydrated",
    Thirst_3_2 = "I'm getting dizzy",
    Thirst_3_3 = "I'm disoriented",
    Thirst_4_1 = "I can't take it anymore, I need water now",
    Thirst_4_2 = "I can't go on without water",
    Thirst_4_3 = "I'm about to pass out",

    Tired_1_1 = "My eyes are heavy",
    Tired_1_2 = "I'm tired",
    Tired_1_3 = "I need to rest",
    Tired_2_1 = "I need to sleep",
    Tired_2_2 = "I can't stop yawning",
    Tired_2_3 = "I can't perform well without sleep",
    Tired_3_1 = "I'm exhausted",
    Tired_3_2 = "Everything takes twice as long",
    Tired_3_3 = "I can't even think, I'm so tired",
    Tired_4_1 = "I can't stay awake, this isn't human",
    Tired_4_2 = "If I don't sleep soon I'm going to die",
    Tired_4_3 = "I'm so tired I can't even keep my eyes open",

    Hungry_1_1 = "I could eat something",
    Hungry_1_2 = "I'm a bit hungry",
    Hungry_1_3 = "I haven't eaten in a while",
    Hungry_2_1 = "I'm really hungry",
    Hungry_2_2 = "My stomach is empty",
    Hungry_2_3 = "I'm running low on energy",
    Hungry_3_1 = "I'm starving, I have no strength left",
    Hungry_3_2 = "I'm so hungry my stomach hurts",
    Hungry_3_3 = "I need to eat something now",
    Hungry_4_1 = "If I don't eat something soon I'll pass out",
    Hungry_4_2 = "I can't go on without food",
    Hungry_4_3 = "I'm so hungry I can't even think",

    Panic_1_1 = "Shit",
    Panic_1_2 = "Fuck",
    Panic_1_3 = "Bad business",
    Panic_2_1 = "I'm really scared",
    Panic_2_2 = "This is really bad",
    Panic_2_3 = "I can't handle this",
    Panic_3_1 = "This is a nightmare",
    Panic_3_2 = "I can't believe this is happening",
    Panic_3_3 = "I need to get out of here now",
    Panic_4_1 = "I'm going to die here, there's no way out",
    Panic_4_2 = "It's all over, this is the end",
    Panic_4_3 = "I can't do anything to save myself",

    Sick_1_1 = "Something's wrong",
    Sick_1_2 = "I don't feel well",
    Sick_1_3 = "I feel unwell",
    Sick_2_1 = "I feel sick",
    Sick_2_2 = "I'm nauseous",
    Sick_2_3 = "This is getting worse",
    Sick_3_1 = "I'm sick",
    Sick_3_2 = "I feel terrible",
    Sick_3_3 = "I think I'm going to throw up",
    Sick_4_1 = "This is the end",
    Sick_4_2 = "My whole body hurts",
    Sick_4_3 = "I feel like I'm dying",

    Bored_1_1 = "I'm bored",
    Bored_1_2 = "There's nothing to do",
    Bored_1_3 = "This is dragging on",
    Bored_2_1 = "I need to do something",
    Bored_2_2 = "This is so boring",
    Bored_2_3 = "If I had something to do I wouldn't be so bored",
    Bored_3_1 = "This boredom is killing me",
    Bored_3_2 = "Time isn't moving",
    Bored_3_3 = "This is unbearable",
    Bored_4_1 = "I'm going crazy",
    Bored_4_2 = "Anything would be better than this",
    Bored_4_3 = "I'm going to lose my mind",

    Unhappy_1_1 = "I don't feel good",
    Unhappy_1_2 = "I'm sad",
    Unhappy_1_3 = "I feel down",
    Unhappy_2_1 = "Everything's grey",
    Unhappy_2_2 = "If only I could see another person",
    Unhappy_2_3 = "I need something to cheer me up",
    Unhappy_3_1 = "Nothing matters anymore, I'll die anyway",
    Unhappy_3_2 = "There's no point in continuing to live",
    Unhappy_3_3 = "I'm so depressed I can't even think",
    Unhappy_4_1 = "I don't want to keep living, what's the point of all this",
    Unhappy_4_2 = "I miss my family, my friends, my previous life",
    Unhappy_4_3 = "I'm a wretch, why keep living if I have nothing and no one",

    Bleeding_1_1 = "I'm bleeding",
    Bleeding_1_2 = "I have an open wound",
    Bleeding_1_3 = "I should watch that wound",
    Bleeding_2_1 = "This won't stop, I need to bandage it soon",
    Bleeding_2_2 = "I keep losing blood",
    Bleeding_2_3 = "If I don't treat this it'll get worse",
    Bleeding_3_1 = "I'm losing a lot of blood, I don't know how much longer I can hold on",
    Bleeding_3_2 = "I'm bleeding out",
    Bleeding_3_3 = "I feel weak from blood loss",
    Bleeding_4_1 = "I can't... stop the bleeding..., this is the end...",
    Bleeding_4_2 = "It's so... cold... all of a sudden...",
    Bleeding_4_3 = "Someone... please... help me... I'm... dying...",

    Wet_1_1 = "I'm wet",
    Wet_1_2 = "How uncomfortable",
    Wet_1_3 = "This is unpleasant",
    Wet_2_1 = "I'm soaked",
    Wet_2_2 = "This won't dry",
    Wet_2_3 = "I should find a dry place",
    Wet_3_1 = "If I don't dry off soon, I'm going to catch a cold",
    Wet_3_2 = "I'm going to get sick like this",
    Wet_3_3 = "This is unbearable, I need to dry off",
    Wet_4_1 = "I'm soaked to the bone",
    Wet_4_2 = "I can't stand this dampness anymore",
    Wet_4_3 = "This is like being in a pool",

    HasACold_1_1 = "I think I'm catching a cold",
    HasACold_1_2 = "My nose is stuffed",
    HasACold_1_3 = "I'm sneezing",
    HasACold_2_1 = "I can't stop sneezing",
    HasACold_2_2 = "My head hurts",
    HasACold_2_3 = "My nose won't stop running",
    HasACold_3_1 = "I feel terrible, I can't stop coughing",
    HasACold_3_2 = "I have a fever",
    HasACold_3_3 = "I'm wrecked",
    HasACold_4_1 = "I'm dying while alive",
    HasACold_4_2 = "This situation is miserable",
    HasACold_4_3 = "I can't even think clearly",

    Injured_1_1 = "I'm injured",
    Injured_1_2 = "Something's not right",
    Injured_1_3 = "I should check my wounds",
    Injured_2_1 = "It hurts when I move",
    Injured_2_2 = "This is limiting me",
    Injured_2_3 = "If I don't heal this it'll get worse",
    Injured_3_1 = "I can't move",
    Injured_3_2 = "My body isn't responding well",
    Injured_3_3 = "I'm seriously injured",
    Injured_4_1 = "I'm done for",
    Injured_4_2 = "I won't recover from this",
    Injured_4_3 = "This is the end for me",

    Pain_1_1 = "Something hurts",
    Pain_1_2 = "It stings",
    Pain_1_3 = "I feel an annoying pain",
    Pain_2_1 = "This hurts too much",
    Pain_2_2 = "I can't concentrate with this pain",
    Pain_2_3 = "The pain is affecting me",
    Pain_3_1 = "The pain is unbearable",
    Pain_3_2 = "The pain won't stop",
    Pain_3_3 = "My whole body hurts now",
    Pain_4_1 = "I'd rather die than continue like this",
    Pain_4_2 = "I can't bear this pain one more second",
    Pain_4_3 = "This is worse than death",

    Drunk_1_1 = "I'm feeling good",
    Drunk_1_2 = "This is fun",
    Drunk_1_3 = "I feel good",
    Drunk_2_1 = "I can't walk straight",
    Drunk_2_2 = "Fuck, I'm drunk",
    Drunk_2_3 = "I'm having trouble keeping my balance",
    Drunk_3_1 = "Everything's spinning",
    Drunk_3_2 = "I don't even know where I am",
    Drunk_3_3 = "I'm completely drunk",
    Drunk_4_1 = "I think... I think I'm gonna... puke",
    Drunk_4_2 = "I'm flyyyiiing... through... THROUGH SPAAACE... yeeehaaaw",
    Drunk_4_3 = "Let's kill that zombie... or me... or both... wooohooo",

    FoodEaten_1_1 = "A bite never hurts",
    FoodEaten_1_2 = "Good, this will help",
    FoodEaten_2_1 = "I feel better",
    FoodEaten_2_2 = "This helps me keep going",
    FoodEaten_2_3 = "This is just what I needed",
    FoodEaten_3_1 = "I feel more energized",
    FoodEaten_3_2 = "I'm full",
    FoodEaten_3_3 = "With this I can keep fighting",
    FoodEaten_4_1 = "I'm bursting with so much food",
    FoodEaten_4_2 = "I can't even move I'm so full",
    FoodEaten_4_3 = "That was too much food, I feel sick",

    Hyperthermia_1_1 = "I'm hot",
    Hyperthermia_1_2 = "I'm sweating",
    Hyperthermia_1_3 = "It's hot in here",
    Hyperthermia_2_1 = "I'm sweating a lot",
    Hyperthermia_2_2 = "This is unbearable",
    Hyperthermia_2_3 = "I should find a cool place",
    Hyperthermia_3_1 = "I can't stand this heat, I need to cool down now",
    Hyperthermia_3_2 = "I'm dehydrating from the heat",
    Hyperthermia_3_3 = "This is a sauna, I can't take it",
    Hyperthermia_4_1 = "This is hell, I'm going to get heat stroke",
    Hyperthermia_4_2 = "My head is burning and my blood is boiling",
    Hyperthermia_4_3 = "I can't stand one more second of this heat",

    Hypothermia_1_1 = "I'm cold",
    Hypothermia_1_2 = "It's cold in here",
    Hypothermia_1_3 = "I need some warmth",
    Hypothermia_2_1 = "I need to warm up",
    Hypothermia_2_2 = "I'm shivering",
    Hypothermia_2_3 = "The cold is affecting me",
    Hypothermia_3_1 = "I'm freezing",
    Hypothermia_3_2 = "I'm numb from the cold",
    Hypothermia_3_3 = "I can't feel my fingers",
    Hypothermia_4_1 = "I can't feel my extremities, I can't even think",
    Hypothermia_4_2 = "This is the end, I'm dying of hypothermia",
    Hypothermia_4_3 = "I'm so frozen I can't even move",

    Uncomfortable_1_1 = "Something's bothering me",
    Uncomfortable_1_2 = "I don't feel well",
    Uncomfortable_1_3 = "This isn't pleasant",
    Uncomfortable_2_1 = "This is too uncomfortable",
    Uncomfortable_2_2 = "I can't concentrate with this",
    Uncomfortable_2_3 = "I need to fix this",
    Uncomfortable_3_1 = "I can't stand this situation anymore",
    Uncomfortable_3_2 = "This situation is overwhelming me",
    Uncomfortable_3_3 = "I want to stop this now",
    Uncomfortable_4_1 = "This is unbearable, I can't stand it anymore",
    Uncomfortable_4_2 = "Enough already, this is horrible",
    Uncomfortable_4_3 = "I can't bear this one more second",

    NoxiousSmell_1_1 = "Something smells bad here",
    NoxiousSmell_1_2 = "There's an unpleasant smell",
    NoxiousSmell_1_3 = "This place reeks",
    NoxiousSmell_2_1 = "This smell is disgusting",
    NoxiousSmell_2_2 = "This smell is making me dizzy",
    NoxiousSmell_2_3 = "This is unbearable, I need to get away from here",
    NoxiousSmell_3_1 = "I can't stand this smell, I'm going to get sick",
    NoxiousSmell_3_2 = "This smell is turning my stomach",
    NoxiousSmell_3_3 = "I think I'm going to throw up from this smell",
    NoxiousSmell_4_1 = "I can't breathe properly, this is terrible",
    NoxiousSmell_4_2 = "I can't take it anymore, I think I'm going to pass out",
    NoxiousSmell_4_3 = "I have to get out of here now",

    -- Reading thoughts
    SkillBook_1 = "I learned something useful",
    SkillBook_2 = "Knowledge is power in this world",
    SkillBook_3 = "This will help me survive",
    SkillBook_4 = "I should practice this",
    
    RecipeBook_1 = "Now I know how to make this",
    RecipeBook_2 = "This recipe could be useful",
    RecipeBook_3 = "I'll try this when I can",
    
    Novel_1 = "That was a good read",
    Novel_2 = "At least I distracted myself for a while",
    Novel_3 = "I needed that mental break",
    Novel_4 = "That helped clear my mind",
}

LivingSurvivorLang["ES"] = {

    -- Moodle thoughts
    Endurance_1_1 = "Respira...",
    Endurance_1_2 = "Aguanto un poco mas",
    Endurance_1_3 = "Concentrate en sobrevivir",
    Endurance_2_1 = "Me falta el aire",
    Endurance_2_2 = "Estoy forzando demasiado",
    Endurance_2_3 = "Los pulmones me arden",
    Endurance_3_1 = "Estoy reventado",
    Endurance_3_2 = "Estoy al limite",
    Endurance_3_3 = "La fatiga me esta destruyendo",
    Endurance_4_1 = "No... puedo... ni moverme",
    Endurance_4_2 = "Ya no me quedan fuerzas",
    Endurance_4_3 = "Casi no puedo respirar",

    HeavyLoad_1_1 = "Esto pesa",
    HeavyLoad_1_2 = "Llevo demasiadas cosas",
    HeavyLoad_1_3 = "Esto es un lastre",
    HeavyLoad_2_1 = "Deberia soltar algo",
    HeavyLoad_2_2 = "Esto me esta ralentizando",
    HeavyLoad_2_3 = "No puedo correr con esto",
    HeavyLoad_3_1 = "El peso me esta destrozando",
    HeavyLoad_3_2 = "No puedo ni caminar con esto",
    HeavyLoad_3_3 = "La espalda me duele demasiado",
    HeavyLoad_4_1 = "No... puedo... mas...",
    HeavyLoad_4_2 = "Si no suelto algo tendre un accidente",
    HeavyLoad_4_3 = "El peso me esta matando lentamente",

    Angry_1_1 = "Que fastidio",
    Angry_1_2 = "Estoy cabreado",
    Angry_1_3 = "No estoy de humor",
    Angry_2_1 = "Todo sale mal",
    Angry_2_2 = "Estoy perdiendo la paciencia",
    Angry_2_3 = "Esto me esta poniendo de los nervios",
    Angry_3_1 = "Que puta mierda, estoy harto",
    Angry_3_2 = "Me encantaria rompler algo",
    Angry_3_3 = "Estoy a punto de explotar",
    Angry_4_1 = "Voy a destrozar todo",
    Angry_4_2 = "Estoy hasta los putos cojones de esta mierda",
    Angry_4_3 = "Los voy a matar a todos",

    Stress_1_1 = "Que estres",
    Stress_1_2 = "Estoy tenso",
    Stress_1_3 = "Estoy de los nervios",
    Stress_2_1 = "Joder no puedo mas",
    Stress_2_2 = "No paro de darle vueltas",
    Stress_2_3 = "La cabeza me da vueltas",
    Stress_3_1 = "Esto me supera, no puedo con mi vida",
    Stress_3_2 = "La presion me va a matar",
    Stress_3_3 = "Estoy a punto de romperme",
    Stress_4_1 = "No puedo aguantar ni un segundo mas, que acabe ya por Dios",
    Stress_4_2 = "Que pare ya por favor",
    Stress_4_3 = "Por el amor de Dios que termine esto ya",

    Thirst_1_1 = "Un trago vendria bien",
    Thirst_1_2 = "Tengo sed",
    Thirst_1_3 = "Tengo la boca seca",
    Thirst_2_1 = "Necesito beber algo",
    Thirst_2_2 = "La garganta me arde",
    Thirst_2_3 = "Debo beber o empeorare",
    Thirst_3_1 = "Me estoy deshidratando",
    Thirst_3_2 = "Me estoy mareando",
    Thirst_3_3 = "Estoy desorientado",
    Thirst_4_1 = "No aguanto mas, necesito agua ya",
    Thirst_4_2 = "No puedo seguir sin agua",
    Thirst_4_3 = "Estoy a punto de desmayarme",

    Tired_1_1 = "Me pesan los ojos",
    Tired_1_2 = "Estoy cansado",
    Tired_1_3 = "Necesito descansar",
    Tired_2_1 = "Necesito dormir",
    Tired_2_2 = "No paro de bostezar",
    Tired_2_3 = "No rindo bien sin dormir",
    Tired_3_1 = "Estoy agotado",
    Tired_3_2 = "Todo me cuesta el doble",
    Tired_3_3 = "No puedo ni pensar de lo cansado que estoy",
    Tired_4_1 = "No puedo seguir despierto, esto no es humano",
    Tired_4_2 = "Si no duermo pronto voy a morir",
    Tired_4_3 = "Estoy tan cansado que ya no puedo ni mantener los ojos abiertos",

    Hungry_1_1 = "Podria comer algo",
    Hungry_1_2 = "Tengo algo de hambre",
    Hungry_1_3 = "No he comido en un rato",
    Hungry_2_1 = "Tengo mucha hambre",
    Hungry_2_2 = "El estomago esta vacio",
    Hungry_2_3 = "Me falta energia",
    Hungry_3_1 = "Estoy hambriento, ya no tengo fuerzas",
    Hungry_3_2 = "Estoy tan hambriento que me duele el estomago",
    Hungry_3_3 = "Necesito comer algo ya",
    Hungry_4_1 = "Si no como algo pronto voy a desmayarme",
    Hungry_4_2 = "No puedo seguir sin comer",
    Hungry_4_3 = "Estoy tan hambriento que ya no puedo ni pensar",

    Panic_1_1 = "Mierda",
    Panic_1_2 = "Joder",
    Panic_1_3 = "Mal asunto",
    Panic_2_1 = "Tengo mucho miedo",
    Panic_2_2 = "Esto es muy malo",
    Panic_2_3 = "No puedo con esto",
    Panic_3_1 = "Esto es una pesadilla",
    Panic_3_2 = "No puedo creer que esto este pasando",
    Panic_3_3 = "Tengo que huir de aqui ya",
    Panic_4_1 = "Voy a morir aqui, no hay salida",
    Panic_4_2 = "Se acabo todo, esto es el fin",
    Panic_4_3 = "No puedo hacer nada para salvarme",

    Sick_1_1 = "Algo va mal",
    Sick_1_2 = "No me encuentro bien",
    Sick_1_3 = "Tengo mal cuerpo",
    Sick_2_1 = "Me siento mal",
    Sick_2_2 = "Tengo nauseas",
    Sick_2_3 = "Esto empeora",
    Sick_3_1 = "Estoy enfermo",
    Sick_3_2 = "Estoy fatal",
    Sick_3_3 = "Creo que voy a vomitar",
    Sick_4_1 = "Esto es el fin",
    Sick_4_2 = "Me duele todo el cuerpo",
    Sick_4_3 = "Siento que me estoy muriendo",

    Bored_1_1 = "Me aburro",
    Bored_1_2 = "No hay nada que hacer",
    Bored_1_3 = "Esto se hace largo",
    Bored_2_1 = "Necesito hacer algo",
    Bored_2_2 = "Esto es tan aburrido",
    Bored_2_3 = "Si hubiera algo que hacer no me aburriria tanto",
    Bored_3_1 = "Este aburrimiento me mata",
    Bored_3_2 = "El tiempo no avanza",
    Bored_3_3 = "Esto es insoportable",
    Bored_4_1 = "Me estoy volviendo loco",
    Bored_4_2 = "Cualquier cosa seria mejor que esto",
    Bored_4_3 = "Voy a perder la cabeza",

    Unhappy_1_1 = "No me siento bien",
    Unhappy_1_2 = "Estoy triste",
    Unhappy_1_3 = "Me noto apagado",
    Unhappy_2_1 = "Todo es gris",
    Unhappy_2_2 = "Si tan solo pudiese ver a otra persona",
    Unhappy_2_3 = "Necesito algo que me alegre",
    Unhappy_3_1 = "Nada importa ya, morire igualmente",
    Unhappy_3_2 = "No hay sentido en seguir viviendo",
    Unhappy_3_3 = "Estoy tan deprimido que ya no puedo ni pensar",
    Unhappy_4_1 = "No quiero seguir viviendo, que sentido tiene todo esto",
    Unhappy_4_2 = "Echo de menos a mi familia, a mis amigos, a mi vida anterior",
    Unhappy_4_3 = "Soy un desgraciado, para que seguir viviendo si no tengo nada ni nadie",

    Bleeding_1_1 = "Estoy sangrando",
    Bleeding_1_2 = "Tengo una herida abierta",
    Bleeding_1_3 = "Deberia vigilar esa herida",
    Bleeding_2_1 = "Esto no para, necesito vendarme pronto",
    Bleeding_2_2 = "Sigo perdiendo sangre",
    Bleeding_2_3 = "Si no me curo esto va a empeorar",
    Bleeding_3_1 = "Estoy perdiendo mucha sangre, no se cuanto mas aguantare",
    Bleeding_3_2 = "Me estoy desangrando",
    Bleeding_3_3 = "Me siento debil por la perdida de sangre",
    Bleeding_4_1 = "No puedo... detener la sangre..., esto es el fin...",
    Bleeding_4_2 = "Que frio... hace... de repente...",
    Bleeding_4_3 = "Alguien... por favor... que me ayude... estoy... muriendo...",

    Wet_1_1 = "Estoy mojado",
    Wet_1_2 = "Que incomodo",
    Wet_1_3 = "Esto es desagradable",
    Wet_2_1 = "Estoy empapado",
    Wet_2_2 = "Esto no se seca",
    Wet_2_3 = "Deberia buscar un lugar seco",
    Wet_3_1 = "Si no me seco pronto, me voy a resfriar",
    Wet_3_2 = "Asi voy a enfermarme",
    Wet_3_3 = "Esto es insoportable, necesito secarme",
    Wet_4_1 = "Estoy calado hasta los huesos",
    Wet_4_2 = "No puedo soportar mas esta humedad",
    Wet_4_3 = "Esto es como estar en una piscina",

    HasACold_1_1 = "Creo que me estoy resfriando",
    HasACold_1_2 = "Tengo la nariz tapada",
    HasACold_1_3 = "Estoy estornudando",
    HasACold_2_1 = "No paro de estornudar",
    HasACold_2_2 = "Me duele la cabeza",
    HasACold_2_3 = "No paro de moquear",
    HasACold_3_1 = "Me siento fatal, no paro de toser",
    HasACold_3_2 = "Estoy con fiebre",
    HasACold_3_3 = "Estoy hecho polvo",
    HasACold_4_1 = "Me estoy muriendo en vida",
    HasACold_4_2 = "Esta situacion es miserable",
    HasACold_4_3 = "No puedo ni siquiera pensar con claridad",

    Injured_1_1 = "Estoy herido",
    Injured_1_2 = "Algo no va bien",
    Injured_1_3 = "Deberia revisar mis heridas",
    Injured_2_1 = "Me duele al moverme",
    Injured_2_2 = "Esto me esta limitando",
    Injured_2_3 = "Si no me curo esto va a empeorar",
    Injured_3_1 = "No soy capaz de moverme",
    Injured_3_2 = "Mi cuerpo no responde bien",
    Injured_3_3 = "Estoy gravemente herido",
    Injured_4_1 = "Estoy acabado",
    Injured_4_2 = "De esto ya no me recupero",
    Injured_4_3 = "Esto es el fin para mi",

    Pain_1_1 = "Algo me duele",
    Pain_1_2 = "Escuece",
    Pain_1_3 = "Noto un dolor molesto",
    Pain_2_1 = "Esto duele demasiado",
    Pain_2_2 = "No puedo concentrarme con este dolor",
    Pain_2_3 = "El dolor me esta afectando",
    Pain_3_1 = "El dolor es insoportable",
    Pain_3_2 = "El dolor no para",
    Pain_3_3 = "Ya me duele todo el cuerpo",
    Pain_4_1 = "Prefiero morir a seguir asi",
    Pain_4_2 = "No puedo soportar este dolor ni un segundo mas",
    Pain_4_3 = "Esto es peor que la muerte",

    Drunk_1_1 = "Voy alegre",
    Drunk_1_2 = "Esto es divertido",
    Drunk_1_3 = "Me siento bien",
    Drunk_2_1 = "No camino recto",
    Drunk_2_2 = "Joder, estoy borracho",
    Drunk_2_3 = "Me cuesta mantener el equilibrio",
    Drunk_3_1 = "Todo gira",
    Drunk_3_2 = "No se ni donde estoy",
    Drunk_3_3 = "Estoy completamente borracho",
    Drunk_4_1 = "Creo que... creo que voy a... vomitar",
    Drunk_4_2 = "Estoyy vo-volandooo... por... POR EL ESPACIOOO... yeeehaaa",
    Drunk_4_3 = "Vamoss a matar a ese zombi... o a mi... o a los dos... wooohooo",

    FoodEaten_1_1 = "Un bocado nunca viene mal",
    FoodEaten_1_2 = "Bien, esto me va a ayudar",
    FoodEaten_2_1 = "Me siento mejor",
    FoodEaten_2_2 = "Me ayuda a seguir adelante",
    FoodEaten_2_3 = "Esto es justo lo que necesitaba",
    FoodEaten_3_1 = "Me siento con mas energia",
    FoodEaten_3_2 = "Estoy lleno",
    FoodEaten_3_3 = "Con esto puedo seguir luchando",
    FoodEaten_4_1 = "Estoy que reviento de tanta comida",
    FoodEaten_4_2 = "No puedo ni moverme de lo lleno que estoy",
    FoodEaten_4_3 = "Eso fue demasiada comida, me siento mal",

    Hyperthermia_1_1 = "Tengo calor",
    Hyperthermia_1_2 = "Estoy sudando",
    Hyperthermia_1_3 = "Que calor hace aqui",
    Hyperthermia_2_1 = "Estoy sudando mucho",
    Hyperthermia_2_2 = "Esto es insoportable",
    Hyperthermia_2_3 = "Deberia encontrar un lugar fresco",
    Hyperthermia_3_1 = "No puedo soportar este calor, necesito refrescarme ya",
    Hyperthermia_3_2 = "Me estoy deshidratando por el calor",
    Hyperthermia_3_3 = "Esto es una sauna, no puedo aguantarlo",
    Hyperthermia_4_1 = "Esto es el infierno, me va a dar una insolacion",
    Hyperthermia_4_2 = "Me arde la cabeza y me hierve la sangre",
    Hyperthermia_4_3 = "No puedo soportar ni un segundo mas este calor",

    Hypothermia_1_1 = "Tengo frio",
    Hypothermia_1_2 = "Que frio hace aqui",
    Hypothermia_1_3 = "Necesito algo de abrigo",
    Hypothermia_2_1 = "Debo de entrar en calor",
    Hypothermia_2_2 = "Estoy tiritando",
    Hypothermia_2_3 = "El frio me esta afectando",
    Hypothermia_3_1 = "Me estoy congelando",
    Hypothermia_3_2 = "Estoy entumecido por el frio",
    Hypothermia_3_3 = "No me siento los dedos",
    Hypothermia_4_1 = "No puedo sentir mis extremidades, no puedo ni pensar",
    Hypothermia_4_2 = "Esto es el fin, me estoy muriendo de hipotermia",
    Hypothermia_4_3 = "Estoy tan congelado que ya no puedo ni moverme",

    Uncomfortable_1_1 = "Algo me incomoda",
    Uncomfortable_1_2 = "No me siento bien",
    Uncomfortable_1_3 = "Esto no es agradable",
    Uncomfortable_2_1 = "Esto es demasiado incomodo",
    Uncomfortable_2_2 = "No puedo concentrarme con esto",
    Uncomfortable_2_3 = "Necesito arreglar esto",
    Uncomfortable_3_1 = "No aguanto mas esta situacion",
    Uncomfortable_3_2 = "Esta situacion me supera",
    Uncomfortable_3_3 = "Quiero parar esto ya",
    Uncomfortable_4_1 = "Esto es insoportable, no lo aguanto mas",
    Uncomfortable_4_2 = "Basta ya, esto es horrible",
    Uncomfortable_4_3 = "No puedo soportar esto ni un segundo mas",

    NoxiousSmell_1_1 = "Algo huele mal aqui",
    NoxiousSmell_1_2 = "Hay un olor desagradable",
    NoxiousSmell_1_3 = "Este lugar huele fatal",
    NoxiousSmell_2_1 = "Este olor es asqueroso",
    NoxiousSmell_2_2 = "Este olor me esta mareando",
    NoxiousSmell_2_3 = "Esto es insoportable, necesito alejarme de aqui",
    NoxiousSmell_3_1 = "No puedo soportar este olor, voy a enfermar",
    NoxiousSmell_3_2 = "Este olor me esta revolviendo el estomago",
    NoxiousSmell_3_3 = "Creo que voy a vomitar por este olor",
    NoxiousSmell_4_1 = "No puedo respirar bien, esto es terrible",
    NoxiousSmell_4_2 = "No aguanto mas, creo que me voy a desmayar",
    NoxiousSmell_4_3 = "Tengo que salir de aqui ya",

    -- Reading thoughts
    SkillBook_1 = "He aprendido algo util",
    SkillBook_2 = "El conocimiento es poder en este mundo",
    SkillBook_3 = "Esto me ayudara a sobrevivir",
    SkillBook_4 = "Deberia practicar esto",
    
    RecipeBook_1 = "Ahora se como hacer esto",
    RecipeBook_2 = "Esta receta podria ser util",
    RecipeBook_3 = "Lo probare cuando pueda",
    
    Novel_1 = "Ha sido una buena lectura",
    Novel_2 = "Al menos me he distraido un rato",
    Novel_3 = "Necesitaba ese descanso mental",
    Novel_4 = "Eso me ha ayudado a despejarme",
}

-- Alias para variantes de español (sin duplicar memoria)
LivingSurvivorLang["AR"] = LivingSurvivorLang["ES"]